In [31]:
import pandas as pd

In [32]:
projectPath = ('data/World Happiness Report.csv')
educationPath = ('data/DP_LIVE_31032023045926784.csv')

In [33]:
worldHappinessData = pd.read_csv(projectPath)
educationData= pd.read_csv(educationPath)
worldHappinessData

,Country Name,Regional Indicator,Year,Life Ladder,Log GDP Per Capita,Social Support,Healthy Life Expectancy At Birth,Freedom To Make Life Choices,Generosity,Perceptions Of Corruption,Positive Affect,Negative Affect,Confidence In National Government
0,Afghanistan,South Asia,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,South Asia,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,South Asia,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,South Asia,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,South Asia,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2194,Zimbabwe,Sub-Saharan Africa,2018,3.616480,7.783066,0.775388,52.625000,0.762675,-0.051219,0.844209,0.657524,0.211726,0.550508
2195,Zimbabwe,Sub-Saharan Africa,2019,2.693523,7.697755,0.759162,53.099998,0.631908,-0.047464,0.830652,0.658434,0.235354,0.456455
2196,Zimbabwe,Sub-Saharan Africa,2020,3.159802,7.596050,0.717243,53.575001,0.643303,0.006313,0.788523,0.660658,0.345736,0.577302
2197,Zimbabwe,Sub-Saharan Africa,2021,3.154578,7.656878,0.685151,54.049999,0.667636,-0.075575,0.756945,0.609917,0.241682,0.665703
2198,Zimbabwe,Sub-Saharan Africa,2022,3.296220,7.670123,0.666172,54.525002,0.651987,-0.069513,0.752632,0.640609,0.191350,NaN

In [34]:
#Find countries with the highest life expectancy at birth
#Use the LOG gdp Per capita to find happiest country by the gdp
#Countries with the highest confidence in national government
#countries with the highest perception of corruption
#life ladder is a scale from 0 to 10 in which respondents were to think of a ladder with the best possible life  being a 10 https://worldhappiness.report/faq/
50221

50221

In [35]:
educationData.head(14)

   LOCATION INDICATOR SUBJECT   MEASURE FREQUENCY  TIME      Value  Flag Codes
0       AUS  EDUADULT     TRY  PC_25_64         A  2008  36.149986         NaN
1       AUS  EDUADULT     TRY  PC_25_64         A  2009  36.881355         NaN
2       AUS  EDUADULT     TRY  PC_25_64         A  2010  37.604309         NaN
3       AUS  EDUADULT     TRY  PC_25_64         A  2011  38.342072         NaN
4       AUS  EDUADULT     TRY  PC_25_64         A  2012  41.282364         NaN
5       AUS  EDUADULT     TRY  PC_25_64         A  2013  39.539928         NaN
6       AUS  EDUADULT     TRY  PC_25_64         A  2014  41.901855         NaN
7       AUS  EDUADULT     TRY  PC_25_64         A  2015  42.888756         NaN
8       AUS  EDUADULT     TRY  PC_25_64         A  2016  43.743900         NaN
9       AUS  EDUADULT     TRY  PC_25_64         A  2017  45.355675         NaN
10      AUS  EDUADULT     TRY  PC_25_64         A  2018  45.727478         NaN
11      AUS  EDUADULT     TRY  PC_25_64         A  2019  47.129978         NaN
12      AUS  EDUADULT     TRY  PC_25_64         A  2020  49.337452         NaN
13      AUS  EDUADULT     TRY  PC_25_64         A  2021  49.767868         NaN

In [36]:
mean = educationData.groupby(['LOCATION']).mean()['Value']
mean

LOCATION
ARG     21.191401
AUS     42.546641
AUT     30.485423
BEL     37.589922
BRA     15.457381
CAN     54.685492
CHE     39.266515
CHL     22.517932
CHN     14.108245
COL     23.208915
CRI     23.207150
CZE     21.089349
DEU     28.249051
DNK     36.395368
ESP     34.776382
EST     38.385220
FIN     41.804988
FRA     33.585752
G20     30.253283
GBR     43.078846
GRC     28.681753
HUN     23.414702
IDN     10.195973
IND     10.895227
IRL     42.790782
ISL     36.517566
ISR     48.079067
ITA     17.177765
JPN     48.968914
KOR     44.649155
LTU     37.588019
LUX     41.485923
LVA     31.506803
MEX     16.585725
NLD     36.071582
NOR     41.232842
NZL     37.830695
OAVG    34.019624
POL     27.082460
PRT     21.606914
RUS     52.576209
SVK     21.213325
SVN     29.629471
SWE     39.064388
TUR     17.259560
USA     45.029574
ZAF     12.575768
Name: Value, dtype: float64

In [ ]:
#adding a new line